"""Actualizando name varchar table

Revision ID: 6517ab827eb8
Revises: b41d64243976
Create Date: 2023-09-28 23:52:15.739655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6517ab827eb8'
down_revision = 'b41d64243976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.CHAR(length=8),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.CHAR(length=8),
               existing_nullable=True)

    # ### end Alembic commands ###
